'use strict';
const conversation=document.querySelector('#conversation');
const back=document.querySelector('#back');
let history=[],current='home',device='Не указано',symptom='',network='';
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
const check='<span class="check-mark"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg></span>';
const notes={home:['Начинаем с понятного действия','Вместо восьми одинаково заметных пунктов — проба, тарифы и помощь. Личный кабинет остаётся доступным ниже.'],device:['Спрашиваем только нужное','Выбор устройства определяет инструкцию. Придумывать название телефона перед знакомством с условиями не нужно.'],install:['Одна задача на экран','Не даём всю настройку длинной простынёй. Установил приложение — перешёл к добавлению подключения.'],add:['Убираем лишнее копирование','Здесь предлагаем кнопку добавления в приложение. Её реальную работу нужно проверить отдельно для каждой ОС.'],confirm:['Значок VPN — ещё не результат','Просим человека проверить нужный сценарий. «Получилось» — его ответ, а не серверная проверка.'],success:['Фиксируем первый полезный опыт','После подключения показываем, где помощь и управление подпиской. Реферальную рассылку в этот момент не отправляем.'],help:['Помощь без технического экзамена','Спрашиваем, что происходит, а затем — устройство и тип сети. Не просим ключ подписки или пароль.'],plans:['Условия раньше оплаты','Цена, период, устройства и ограничения должны быть видны до покупки. Пока подтверждённых значений нет — не выдумываем.']};
const button=(label,route,kind='')=>`<button class="action ${kind}" data-route="${route}">${label}</button>`;
const row=(a,b)=>`<div class="button-row">${a}${b}</div>`;
function frame(body,actions,reply='',fine=''){
 return `<div class="date">Просмотр макета</div>${reply?`<div class="outgoing">${reply}</div>`:''}<article class="message">${body}<span class="message-time">Updates VPN</span></article><div class="actions">${actions}</div>${fine?`<p class="fine">${fine}</p>`:''}`;
}
function screen(id){
 const os=device;
 switch(id){
 case 'home':return frame('<h2>Давайте подключимся.</h2><p>Начните с <strong>7 дней бесплатно</strong>, чтобы проверить VPN на своём устройстве и в своей сети.</p><p>Покажем шаги настройки. Если не получится — поможем разобраться.</p>',button('Попробовать 7 дней '+arrow,'device','primary')+row(button('Тарифы','plans'),button('Нужна помощь','help'))+button('Моя подписка','account','textual'),'','Макет: цена после теста и его полные условия ещё не внесены. До запуска они должны быть доступны здесь.');
 case 'device':return frame('<h2>На чём подключаем?</h2><p>Покажем инструкцию для вашего устройства.</p>',button('Android','os-android','primary')+button('iPhone','os-iphone')+button('Компьютер','os-desktop')+button('Нужна помощь','help','textual'),'Попробовать 7 дней','Это пример выбора устройства. Пробная подписка не создаётся.');
 case 'desktop':return frame('<h2>Какая система?</h2><p>От неё зависит приложение и инструкция.</p>',button('Windows','os-windows','primary')+button('macOS','os-macos')+button('Другая система','other-system','textual'),'Компьютер');
 case 'other-system':return frame('<h2>Уточним совместимость.</h2><p>Для другой системы лучше сначала проверить, какое приложение подойдёт.</p>',button('Подготовить вопрос','support','primary')+button('Выбрать другое устройство','device','textual'),'Другая система');
 case 'install':return frame(`<span class="step">Настройка · шаг 1 из 3</span><h2>Установите приложение.</h2><p>Для подключения на ${os==='компьютере'?device:os} понадобится приложение <strong>Happ</strong>.</p><p class="muted">В рабочем боте кнопка будет вести на проверенную страницу приложения для вашей системы.</p>`,button('Посмотреть шаг установки '+arrow,'store','primary')+button('Уже установлено','add')+button('Нужна помощь','help','textual'),device,'Показан пример инструкции. Ссылки и совместимость для каждой ОС нужно проверить перед внедрением.');
 case 'store':return frame('<h2>После установки — сюда.</h2><p>Установите приложение и вернитесь в бот, чтобы добавить подключение.</p><p class="muted">В макете магазин приложений не открывается. Нажмите кнопку ниже, чтобы посмотреть следующий шаг.</p>',button('Приложение установлено','add','primary')+button('Не получается установить','help','textual'),'Установить приложение');
 case 'add':return frame('<span class="step">Настройка · шаг 2 из 3</span><h2>Добавьте подключение.</h2><p>Кнопка откроет приложение и передаст в него вашу подписку.</p><p class="muted">Если приложение попросит разрешить добавление — подтвердите его.</p>',button('Добавить в приложение '+arrow,'confirm','primary')+button('Не открывается приложение','add-help')+button('Нужна помощь','help','textual'),'Приложение установлено','Здесь кнопка только показывает следующий экран. Настоящего ключа и передачи подписки в макете нет.');
 case 'confirm':return frame('<span class="step">Настройка · шаг 3 из 3</span><h2>Проверьте подключение.</h2><p>В приложении включите VPN. Затем проверьте, работает ли нужный вам сайт или приложение.</p><p><strong>Всё получилось?</strong></p>',button('Да, получилось','success','primary')+button('Нет, нужна помощь','help'),'Добавить подключение','Подключение не проверяется автоматически. В этом макете все действия демонстрационные.');
 case 'success':return frame(check+'<h2>Отлично, вы разобрались.</h2><p>Теперь вы знаете, как включить VPN. Если возникнет проблема, помощь всегда можно найти в меню бота.</p><p class="muted">В рабочем боте здесь будут срок вашей подписки и кнопка управления ею.</p>',button('Моя подписка','account','primary')+button('Нужна помощь','help')+button('Вернуться в начало','home','textual'),'Да, получилось','Это завершение демонстрации. VPN не подключён, тестовый период не активирован.');
 case 'plans':return frame('<h2>Сначала — условия.</h2><p>Проверьте, подходит ли вам сервис, прежде чем оплачивать подписку.</p><div class="info-row"><span>Пробный период</span><strong>7 дней*</strong></div><div class="info-row"><span>Стоимость</span><strong>Уточняется</strong></div><div class="info-row"><span>Устройства и лимиты</span><strong>Уточняются</strong></div><p class="muted">* Так указано в публичном описании бота. Полные условия теста ещё нужно подтвердить.</p>',button('Посмотреть путь подключения','device','primary')+button('Вопрос об условиях','support')+button('Соглашение и конфиденциальность','terms','textual'),'Тарифы','Цена не придумана. Покупка здесь недоступна; перед запуском этот экран заполняется реальными условиями.');
 case 'account':return frame('<h2>Ваша подписка.</h2><p>У нового пользователя здесь появится подписка после начала теста или оплаты.</p><p class="muted">Это пустое состояние макета. Данные настоящего аккаунта не загружались.</p>',button('Посмотреть подключение','device','primary')+button('Тарифы','plans')+button('Нужна помощь','help','textual'),'Моя подписка');
 case 'terms':return frame('<h2>Условия сервиса.</h2><p>Здесь будут действующие пользовательское соглашение, политика конфиденциальности и правила возврата.</p><p class="muted">Их тексты не подменяем вымышленными документами. Ссылки добавим после проверки команды.</p>',button('Вернуться к тарифам','plans','primary')+button('Задать вопрос','support'),'Соглашение и конфиденциальность');
 case 'help':return frame('<h2>На каком шаге проблема?</h2><p>Выберите похожую ситуацию. Начнём с неё.</p>',button('Не могу настроить','issue-setup','primary')+button('Перестало подключаться','issue-connection')+button('Подключено, но не работает','issue-traffic')+button('Вопрос по оплате','issue-payment')+button('Другой вопрос','support','textual'),'Нужна помощь');
 case 'help-device':return frame('<h2>Какое у вас устройство?</h2><p>Это поможет подобрать нужные шаги.</p>',button('Android','help-android','primary')+button('iPhone','help-iphone')+button('Компьютер','help-desktop'),symptom);
 case 'network':return frame('<h2>Какая сейчас сеть?</h2><p>Проблема может проявляться только в одной сети.</p>',button('Wi-Fi','net-wifi','primary')+button('Мобильный интернет','net-mobile')+button('Не знаю','net-unknown','textual'),device);
 case 'diagnose':return frame('<h2>Проверим один шаг.</h2><p>Выключите и снова включите подключение в приложении. Затем ещё раз проверьте нужный вам сервис.</p><p><strong>Что получилось?</strong></p>',button('Теперь работает','resolved','primary')+button('Не помогло — нужна поддержка','support'),network,'Пример первого шага диагностики. Окончательные инструкции команда проверит на реальных устройствах.');
 case 'add-help':return frame('<h2>Приложение не открылось?</h2><p>Сначала проверьте, установлено ли оно. Если установлено, но кнопка не срабатывает — передайте проблему в поддержку.</p>',button('Вернуться к установке','install','primary')+button('Подготовить обращение','support'),'Не открывается приложение');
 case 'resolved':return frame(check+'<h2>Хорошо, что заработало.</h2><p>Если проблема повторится, вернитесь в «Нужна помощь» и укажите, что уже пробовали.</p>',button('На главную','home','primary')+button('Моя подписка','account'),'Теперь работает');
 case 'support':return frame('<h2>Поможем разобраться.</h2><p>В настоящем боте передадим специалисту выбранные вами сведения, чтобы не спрашивать всё заново.</p><p><strong>Что добавить:</strong> когда появилась проблема и что происходит на экране.</p><p class="muted">Пароль и полный ключ подписки присылать не нужно.</p>',button('Посмотреть обращение','request','primary')+button('Назад к помощи','help','textual'),'Обратиться в поддержку','Это просмотр макета. Сообщение никому не отправляется.');
 case 'request':return frame('<h2>Пример обращения</h2>'+`<p><strong>Проблема:</strong> ${symptom||'Нужна консультация'}<br><strong>Устройство:</strong> ${device}<br><strong>Сеть:</strong> ${network||'Не указана'}</p>`+'<p>В рабочей версии человек сможет дополнить эти сведения и отправить сообщение специалисту.</p><p class="muted">Часы поддержки и ожидаемое время ответа должны быть указаны здесь после согласования.</p>',button('Вернуться на главную','home','primary')+button('Посмотреть другой случай','help'),'Подготовить обращение','Ничего не отправлено. Это пример того, что увидит пользователь перед обращением.');
 default:return screen('home');
 }
}
function go(route,remember=true){
 let id=route;
 const previous={id:current,device,symptom,network};
 if(route.startsWith('os-')){device=({android:'Android',iphone:'iPhone',desktop:'Компьютер',windows:'Windows',macos:'macOS'})[route.slice(3)];id=device==='Компьютер'?'desktop':'install';}
 if(route.startsWith('issue-')){symptom=({setup:'Не могу настроить',connection:'Перестало подключаться',traffic:'Подключено, но не работает',payment:'Вопрос по оплате'})[route.slice(6)];network='';id=route==='issue-payment'?'support':'help-device';}
 if(route.startsWith('help-')&&route!=='help-device'){device=({android:'Android',iphone:'iPhone',desktop:'Компьютер'})[route.slice(5)];id='network';}
 if(route.startsWith('net-')){network=({wifi:'Wi-Fi',mobile:'Мобильный интернет',unknown:'Не знаю'})[route.slice(4)];id='diagnose';}
 if(remember&&id!==current)history.push(previous);
 if(id==='home'){history=[];device='Не указано';symptom='';network='';}
 current=id;conversation.innerHTML=screen(id);back.disabled=history.length===0;
 const family=['help','help-device','network','diagnose','resolved','support','request','add-help','other-system'].includes(id)?'help':['plans','terms'].includes(id)?'plans':'home';
 document.querySelectorAll('.scenario').forEach(b=>{const active=b.dataset.route===family;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','true');else b.removeAttribute('aria-current');});
 const note=notes[id]||notes[family];document.querySelector('#note-title').textContent=note[0];document.querySelector('#note-text').textContent=note[1];
 document.querySelector('#demo-caption').textContent=id==='home'?'Начните с кнопки «Попробовать 7 дней».':'Можно вернуться назад стрелкой или начать заново.';
 const heading=conversation.querySelector('h2');heading.tabIndex=-1;if(remember)heading.focus({preventScroll:true});
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(b){if(b.classList.contains('scenario')){history=[];device='Не указано';symptom='';network='';}go(b.dataset.route);}});
back.addEventListener('click',()=>{const p=history.pop();if(p){device=p.device;symptom=p.symptom;network=p.network;go(p.id,false);conversation.querySelector('h2').focus({preventScroll:true});}});
document.querySelector('#restart').addEventListener('click',()=>{go('home');});
go('home',false);
